# Generated by Django 5.0.7 on 2024-08-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
