# Generated by Django 5.0.7 on 2024-08-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_remove_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='num',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
